---

- name: Check for Rust
  stat:
    path: '~/.cargo/env'
  become: no
  register: is_rust

- name: Download Rust
  get_url: 
    url: 'https://sh.rustup.rs'
    dest: /tmp/rustup.sh
    mode: 0777
  when: is_rust.stat.exists

- name: Install Rust
  shell: '/tmp/rustup.sh -y'
  become: no
  when: is_rust.stat.exists

- name: Activate Rust
  shell: '. ~/.cargo/env'
  become: no
  when: is_rust.stat.exists

