---

- name: Fish | Install
  apt:
    name: 'fish'

- name: Fish | Check current shell
  shell: 'echo $SHELL'
  register: current_shell
  changed_when: False
  check_mode: no
  become: no

- name: Fish | Set default shell
  expect:
    command: chsh -s /usr/bin/fish
    responses:
      (?i)Password: "{{ user_password }}"
  when: current_shell.stdout.find('/usr/bin/fish') == -1
  become: no

- name: Fish | Download Oh-My-Fish
  get_url:
    url: 'https://get.oh-my.fish'
    dest: /tmp/oh-my.fish
    mode: 0777
  when: current_shell.stdout.find('/usr/bin/fish') == -1

- name: Fish | Install Oh-My-Fish
  shell: '/tmp/oh-my.fish'
  become: no
  when:  (lookup('env', 'OMF_PATH') == '')
  environment:
    CI: '1'

- name: Fish | Cleanup tmp files
  file:
    state: absent
    path: '/tmp/oh-my.fish'

- name: Fish | Remove existing config
  file:
    state: absent
    path: '{{ item  }}'
  become: no
  loop:
    - '~/.config/fish'
    - '~/.config/omf'

- name: Fish | Link dotfiles
  file:
    src: '{{ role_path }}/files/{{ item.src  }}'
    dest: '~/.config/{{ item.dest }}'
    state: link
  loop:
    - { src: 'fish', dest: 'fish' }
    - { src: 'omf', dest: 'omf' }
  become: no

