---

- name: Check if already installed
  stat:
    path: /home/{{ user }}/Apps/firefox/firefox
  register: ffd

- name: Download Firefox Developer Edition from Mozilla
  get_url:
    url: https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US
    dest: /tmp/firefox-dev-edition.tar.gz
  when: ffd.stat.exists == false

- name: Extract archive
  unarchive:
    src: /tmp/firefox-dev-edition.tar.gz
    dest: /home/{{ user }}/Apps
  when: ffd.stat.exists == false

- name: Change ownership
  file:
    path: /home/{{ user }}/Apps/firefox
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0755'
  when: ffd.stat.exists == false

- name: Install .desktop entry
  template:
    src: '{{ role_path }}/files/firefoxDeveloperEdition.desktop'
    dest: '/home/{{ user }}/.local/share/applications/firefoxDeveloperEdition.desktop'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0755'
  when: ffd.stat.exists == false
