---
- hosts: localhost
  user: corwin
  become: True
  become_method: sudo
  vars:
    user: corwin
  roles:
    - system
    - git
    - fish
    - fubarhouse.rust
    - nerd-fonts
    - alacritty
    - lsd

  vars_prompt:
    - name: 'user_password'
      prompt: "YOUR Password"

