---
- hosts: localhost
  user: corwin
  become: True
  become_method: sudo
  vars:
    user: corwin
  roles:
    - system
    - git
    - zsh
    - vim
    - nerd-fonts
    - role: naftulikay.rust-dev
      rust_user: "{{ user }}"
    - alacritty
    - lsd
    - jaredhocutt.jetbrains_toolbox
  vars_prompt:
    - name: 'user_password'
      prompt: "YOUR Password"

