---
- hosts: localhost
  user: corwin
  become: True
  become_method: sudo
  vars:
    user: corwin
  roles:
    - system
    - git
    - zsh
    - vim
    - role: naftulikay.rust-dev
      rust_user: "{{ user }}"
    - lsd
    - firefox-developer
    - jetbrains-toolbox
    - docker
#    - xow
