---
- hosts: localhost
  user: corwin
  become_method: sudo
  vars:
    apps_path: /home/{{ ansible_user_id }}/Apps
  roles:
# Basic things
    - system
    - git
    - zsh
    - vim
    - role: naftulikay.rust-dev
      rust_user: "{{ ansible_user_id }}"
    - lsd
    - nerd_fonts
# Developer things
    - docker
    - jetbrains_toolbox
    - firefox_developer
    - zotero
# Gaming things
    - xow
    - goverlay
    - mangohud
    - vkbasalt
    - replay_sorcery
