---
- hosts: localhost
  user: corwin
  become: True
  become_method: sudo
  vars:
    user: corwin
  roles:
    - system
    - git
    - zsh
    - vim
    - nerd-fonts
    - role: naftulikay.rust-dev
      rust_user: "{{ user }}"
    - alacritty
    - lsd
    - firefox-developer
    - jetbrains-toolbox

