---

- name: Install APT dependencies
  apt:
    name: "{{ item }}"
  loop:
    - libusb-1.0-0-dev
    - cabextract

- name: Clone from git
  git:
    repo: 'https://github.com/medusalix/xow'
    dest: '{{ apps_path }}/xow'
    depth: 1

- name: Verify clone
  stat:
    path: '{{ apps_path }}/xow'
  register: xow_path

- name: Build
  shell: 'make BUILD=RELEASE'
  args:
    chdir: '{{ apps_path }}/xow'
  when: xow_path.stat.exists

- name: Make firmware script executable
  file:
    path: '{{ apps_path }}/xow/firmware.sh'
    mode: '0755'
  when: xow_path.stat.exists

- name: Download firmware
  expect:
    command: './firmware.sh'
    responses:
      '(.*)Do you accept the terms of the agreement(.*)':
        - 'y'
  args:
    chdir: '{{ apps_path }}/xow'
  when: xow_path.stat.exists

- name: Install
  shell: 'make install'
  become: yes
  args:
    chdir: '{{ apps_path }}/xow'
  when: xow_path.stat.exists
  ignore_errors: true

- name: Enable service
  become: yes
  systemd:
    name: xow
    enabled: yes
    state: started

