---
- name: Install APT Packages
  apt:
    name: "{{ item }}"
  loop:
    - htop
    - tmux
    - build-essential
    - tree
    - python3
    - python3-pip
    - psensor
    - lm-sensors
    - flatpak