---

- name: Install APT Packages
  when: ansible_distribution == 'Ubuntu'
  apt:
    name: "{{ item }}"
  loop:
    - htop
    - vim
    - tmux
    - build-essential
    - tree
    - python-pip
    - python3-pip
    - docker
    - docker-compose
  pip:
    name: pexpect

- name: Install DNF Packages
  when: ansible_distribution == 'Fedora'
  dnf:
    name: "{{ item }}"
  loop:
    - htop
    - vim
    - tmux
    - @development-tools
    - tree
    - python-pip
    - docker
    - docker-compose

