---

- name: Install APT Packages
  when: ansible_distribution == 'Ubuntu'
  apt:
    name: "{{ item }}"
  loop:
    - htop
    - vim
    - tmux
    - build-essential
    - tree
    - python3
    - python-pip
    - python3-pip
    - docker
    - docker-compose
  
- name: Install DNF Packages
  when: ansible_distribution == 'Fedora'
  dnf:
    name: "{{ item }}"
  loop:
    - htop
    - vim
    - tmux
    - "@development-tools"
    - tree
    - python2-libselinux
    - python3
    - python-pip
    - docker
    - docker-compose

- name: Install PIP Packages
  pip:
    name: pexpect

