---

- name: Install Packages
  apt:
    name: "{{ item }}"
  loop:
    - fish
    - htop
    - vim
    - tmux
    - git
    - build-essential
    - tree
    - python-pip
    - python3-pip
    - libfreetype6-dev
    - libfontconfig1-dev
    - xclip

- name: Install pexpect
  pip:
    name: pexpect

