---

- name: Install Packages
  apt:
    name: "{{ item }}"
  loop:
    - htop
    - vim
    - tmux
    - build-essential
    - tree
    - python-pip
    - python3-pip

- name: Install pexpect
  pip:
    name: pexpect

