---

- import_tasks: debian.yml
  when: ansible_distribution == 'Pop!_OS'

- import_tasks: debian.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Install Oh-My-Zsh
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: '/home/{{ ansible_user_id }}/.oh-my-zsh'
  become: no

- name: Install Powerline9k theme
  git:
    repo: 'https://github.com/bhilburn/powerlevel9k.git'
    dest: '/home/{{ ansible_user_id }}/.oh-my-zsh/custom/themes/powerlevel9k'
  become: no

- name: Set Zsh as default shell
  user:
    name: '{{ ansible_user_id }}'
    shell: '/usr/bin/zsh'

- name: Link dotfile
  file:
    src: '{{ role_path }}/files/.zshrc'
    dest: '/home/{{ ansible_user_id }}/.zshrc'
    state: link
  become: no

- name: Reset connection
  meta: reset_connection
