---

- import_tasks: debian.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Remove existing dotfile
  file:
    state: absent
    path: '~/.gitconfig'

- name: Link .gitconfig
  file:
    src: '{{ role_path }}/files/gitconfig'
    dest: '~/.gitconfig'
    state: link

- name: Link .gitignore
  file:
    src: '{{ role_path }}/files/gitignore'
    dest: '~/.gitignore'
    state: link
