---

- name: Git | Install
  apt:
    name: '{{ item  }}'
  loop:
    - git
    - git-extras

- name: Git | Remove existing dotfile
  file:
    state: absent
    path: '~/.gitconfig'
  become: no

- name: Git | Link dotfiles
  file:
    src: '{{ role_path  }}/files/gitconfig'
    dest: './gitconfig'
    state: link
  become: no
