---

- name: Clone Alacritty from Git
  git: 
    repo: https://github.com/jwilm/alacritty.git
    dest: '/tmp/alacritty'
    depth: 1

- name: Verify clone
  stat:
    path: '/tmp/alacritty'
  register: alacritty_path

- name: Install Cargo Deb
  shell: 'cargo install cargo-deb'
  become: no
  when: alacritty_path.stat.exists

- name: Install Alacritty
  shell: 'cargo deb --install'
  become: no
  args:
    chdir: '/tmp/alacritty/'
  when: alacritty_path.stat.exists

- name: Check if tmp folder exists
  stat:
    path: '/tmp/alacritty'
  register: tmp_alacritty

- name: Cleanup Alacritty tmp files
  file:
    state: absent
    path: '/tmp/alacritty'
  when: tmp_alacritty.stat.exists

