---

- name: Clone LSD from Git
  git: 
    repo: 'https://github.com/Peltoche/lsd.git' 
    dest: '/tmp/lsd'
    depth: 1

- name: Verify clone
  stat:
    path: '/tmp/lsd'
  register: lsd_path

- name: Install LSD
  shell: 'cargo install lsd'
  become: no
  args:
    chdir: '/tmp/lsd/'
  when: lsd_path.stat.exists

- name: Check if tmp folder exisets
  stat:
    path: '/tmp/lsd'
  register: tmp_lsd

- name: Cleanup LSD tmp files
  file:
    state: absent
    path: '/tmp/lsd'
  when: tmp_lsd.stat.exists

