---

- name: Check if Nerd Fonts are installed
  stat:
    path: '~/.local/share/fonts/NerdFonts/'
  register: nf

- name: Clone Nerd Fonts from Git
  git: 
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: '/tmp/nerd-fonts'
    depth: 1
  when: nf.stat.exists

- name: Verify git clone
  stat:
    path: '/tmp/nerd-fonts'
  register: nf_path

- name: Install Nerd Fonts
  shell: '/tmp/nerd-fonts/install.sh FiraMono FiraCode'
  become: no
  args:
    chdir: '/tmp/nerd-fonts/'
  when: nf_path.stat.exists

- name: Cleanup Nerd Fonts tmp files
  file:
    state: absent
    path: '/tmp/nerd-fonts'

