---
- name: Install lazarus-ide
  become: true
  apt:
    name: lazarus-ide

- name: Install libqt5pas
  become: true
  apt:
    deb: "{{ item }}"
  loop:
    - https://github.com/davidbannon/libqt5pas/releases/download/v1.2.10/libqt5pas1_2.10-0_amd64.deb
    - https://github.com/davidbannon/libqt5pas/releases/download/v1.2.10/libqt5pas-dev_2.10-0_amd64.deb

- name: Clone from git
  git:
    repo: 'git@github.com:benjamimgois/goverlay.git'
    dest: '{{ apps_path }}/goverlay'
    recursive: true

- name: Verify clone
  stat:
    path: '{{ apps_path }}/goverlay'
  register: mh_path

- name: Build
  shell: 'make'
  args:
    chdir: '{{ apps_path }}/goverlay'
  when: mh_path.stat.exists

- name: Install
  become: true
  shell: 'make install'
  args:
    chdir: '{{ apps_path }}/goverlay'
  when: mh_path.stat.exists
