---

- name: LSD | Clone from git
  git: 
    repo: 'https://github.com/Peltoche/lsd.git' 
    dest: '/tmp/lsd'
    depth: 1

- name: LSD | Verify clone
  stat:
    path: '/tmp/lsd'
  register: lsd_path

- name: LSD | Install
  shell: 'cargo install lsd'
  become: no
  args:
    chdir: '/tmp/lsd/'
  when: lsd_path.stat.exists

- name: LSD | Check if tmp folder exists
  stat:
    path: '/tmp/lsd'
  register: tmp_lsd

- name: LSD | Cleanup tmp files
  file:
    state: absent
    path: '/tmp/lsd'
  when: tmp_lsd.stat.exists

