---

- name: Add DNF Repo
  shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    warn: false

- name: Install from DNF
  dnf:
    name: '{{ item }}'
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
