---

#- name: Add APT Repo
#  when: ansible_distribution == 'Ubuntu'
# TODO

- name: Install from APT
  when: ansible_distribution == 'Ubuntu'
  apt:
    name: '{{ item  }}'
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
  
- name: Add DNF Repo
  when: ansible_distribution == 'Fedora'
  shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    warn: false

- name: Install from DNF
  when: ansible_distribution == 'Fedora'
  dnf:
    name: '{{ item }}'
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose

- name: Enable and start service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Create group 'docker'
  group:
    name: docker
    state: present

- name: Add user to 'docker' group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

