---
- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Enable and start service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Create group 'docker'
  group:
    name: docker
    state: present

- name: Add user to 'docker' group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
