---

- name: Check if already installed
  stat:
    path: '/home/{{ ansible_user_id }}/.local/share/fonts/NerdFonts/'
  register: nf

- name: Clone git repo
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: '/tmp/nerd-fonts'
    depth: 1
  when: not nf.stat.exists

- name: Verify clone
  stat:
    path: '/tmp/nerd-fonts'
  register: nf_path


- name: Install
  shell: '/tmp/nerd-fonts/install.sh'

  args:
    chdir: '/tmp/nerd-fonts/'
  when: nf_path.stat.exists

- name: Cleanup tmp files
  file:
    state: absent
    path: '/tmp/nerd-fonts'
