---

- import_tasks: debian.yml
  when: ansible_distribution == 'Pop!_OS'

- import_tasks: debian.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Download Spacevim install script
  get_url:
    url: https://spacevim.org/install.sh
    dest: /tmp/spacevim.sh


- name: Set exec flag on script
  file:
    path: /tmp/spacevim.sh
    state: file
    mode: 0755

- name: Install Spacevim
  shell: ./spacevim.sh
  args:
    chdir: /tmp
