---

- name: Install from APT
  when: ansible_distribution == 'Ubuntu'
  apt:
    name: 'vim'

- name: Install from DNF
  when: ansible_distribution == 'Fedora'
  dnf:
    name: 'vim'

- name: Download Spacevim install script
  get_url:
    url: https://spacevim.org/install.sh
    dest: /tmp/spacevim.sh

- name: Install Spacevim
  shell: ./spacevim.sh
  args:
    chdir: /tmp

