---

- name: Enable Fedora Copr for Alacritty
  command: "dnf copr enable -y pschyska/alacritty"
  creates: /etc/yum.repos.d/_copr_pschyska-alacritty.repo

- name: Install Alacritty from DNF
  dnf:
    name: alacritty
    state: present
