---
- import_tasks: debian.yml
  when: ansible_distribution == 'Pop!_OS'

- import_tasks: debian.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Link dotfiles
  file:
    src: '{{ role_path }}/files/alacritty'
    dest: '/home/{{ user }}/.config/alacritty'
    state: link
