---

- name: Alacritty | Install pre-reqs
  apt:
    name: '{{ item }}'
  loop:
    - libfreetype6-dev
    - libfontconfig1-dev
    - xclip

- name: Alacritty | Verify clone
  stat:
    path: '/tmp/alacritty'
  register: alacritty_path

- name: Alacritty | Install
  shell: '. ~/.cargo/env && cargo install --git https://github.com/jwilm/alacritty'
  args:
    chdir: '/tmp/alacritty/'
  when: alacritty_path.stat.exists
  ignore_errors: True

- name: Alacritty | Link dotfiles
  file:
    src: '{{ role_path }}/files/alacritty'
    dest: '/home/{{ user }}/.config/alacritty'
    state: link

