---

- name: Install pre-reqs from APT
  when: ansible_distribution == 'Ubuntu'
  apt:
    name: '{{ item }}'
  loop:
    - libfreetype6-dev
    - libfontconfig1-dev
    - xclip

- name: Install pre-reqs from DNF
  when: ansible_distribution == 'Fedora'
  dnf:
    name: '{{ item }}'
  loop:
    - freetype-devel
    - fontconfig-devel
    - xclip
    - cmake

- name: Verify clone
  stat:
    path: '/tmp/alacritty'
  register: alacritty_path

- name: Install
  shell: '. ~/.cargo/env && cargo install --git https://github.com/jwilm/alacritty'
  args:
    chdir: '/tmp/alacritty/'
  when: alacritty_path.stat.exists
  ignore_errors: True

- name: Link dotfiles
  file:
    src: '{{ role_path }}/files/alacritty'
    dest: '/home/{{ user }}/.config/alacritty'
    state: link

